version: "3.9"

services:

  spring:
    container_name: smart-home
    build: .
    ports:
      - "5155:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_HOST: smart-home-mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: smart-home-mongo-secret
      DATABASE_NAME: smart_home_prod

    depends_on:
      - mongo


  mongo:
    container_name: smart-home-mongo
    image: mongo:latest
    restart: always
    ports:
      - "3005:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: smart-home-mongo-secret
