version: "3.9"

services:

  spring:
    container_name: iot-booth
    build: .
    ports:
      - "5155:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_HOST: iot-booth-mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: iot-booth-mongo-secret
      DATABASE_NAME: iot_booth_prod

    depends_on:
      - mongo


  mongo:
    container_name: iot-booth-mongo
    image: mongo:latest
    restart: always
    ports:
      - "3005:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: iot-booth-mongo-secret
