spring:
  data:
    mongodb:
      username: root
      password: iot-booth-mongo-secret
      authentication-database: admin
      host: localhost
      port: 3005
      database: iot_booth_prod
#      authentication-mechanism: NONE

